// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-layouts/ActivityPriority.tsx": () => import("../components/mockups/home-layouts/ActivityPriority.tsx"),
  "./components/mockups/home-layouts/CommandCenter.tsx": () => import("../components/mockups/home-layouts/CommandCenter.tsx"),
  "./components/mockups/home-layouts/SidebarStats.tsx": () => import("../components/mockups/home-layouts/SidebarStats.tsx")
};
