#!/usr/bin/env bash
# Auto-generated by task-691. A/B benchmark of vitest poolOptions.maxForks.
# Pre-generates all side-car configs up-front, then runs vitest 3x per setting.
# This avoids mid-benchmark file mutations which would otherwise re-trigger
# Replit's `test`/`lint`/`typecheck` workflows and pollute timings.
set -u
RESULTS=.local/tasks/pool-options-tuning-results.md
LOGDIR=.local/tasks/pool-tuning-logs
mkdir -p "$LOGDIR"
rm -f "$LOGDIR"/*.log "$LOGDIR"/STATUS

emit_default_cfg() {
  cat > "vitest.config.bench-default.ts" <<'EOF'
import baseConfig from './vitest.config';
export default baseConfig;
EOF
}

emit_n_cfg() {
  local n="$1"
  cat > "vitest.config.bench-${n}.ts" <<EOF
import { mergeConfig, defineConfig } from 'vitest/config';
import baseConfig from './vitest.config';

const overrides = defineConfig({
  test: {
    pool: 'forks',
    poolOptions: { forks: { maxForks: ${n}, minForks: ${n} } },
    projects: [
      {
        test: {
          name: 'parallel',
          pool: 'forks',
          poolOptions: { forks: { maxForks: ${n}, minForks: ${n} } },
        },
      },
    ],
  },
});

export default mergeConfig(baseConfig, overrides);
EOF
}

emit_default_cfg
for n in 2 4 6 8; do emit_n_cfg "$n"; done

echo "RUNNING" > "$LOGDIR/STATUS"

CPUS=$(nproc)
MEM_GB=$(awk '/MemTotal/ {printf "%.2f", $2/1024/1024}' /proc/meminfo)
PAR=$(node -e 'console.log(require("os").availableParallelism())')

{
  echo "# pool-options tuning results (task #691)"
  echo
  echo "Container: ${CPUS} CPUs, ${MEM_GB} GB RAM. node availableParallelism = ${PAR}."
  echo
  echo "Started: $(date -Iseconds)"
  echo
  echo "## Per-run results"
  echo
  echo "| setting | run | wall | exit | passed | failed |"
  echo "|---------|-----|------|------|--------|--------|"
} > "$RESULTS"

run_once() {
  local label="$1" idx="$2" cfg="$3"
  local logfile="$LOGDIR/${label}-run${idx}.log"
  local start end dur exit_code fails passes
  start=$(date +%s)
  if npx vitest run --config "$cfg" > "$logfile" 2>&1; then
    exit_code=0
  else
    exit_code=$?
  fi
  end=$(date +%s)
  dur=$((end - start))
  fails=$(grep -E "^[[:space:]]*Tests[[:space:]]+" "$logfile" | tail -1 | grep -oE "[0-9]+ failed" | head -1 | grep -oE "^[0-9]+" || true)
  passes=$(grep -E "^[[:space:]]*Tests[[:space:]]+" "$logfile" | tail -1 | grep -oE "[0-9]+ passed" | head -1 | grep -oE "^[0-9]+" || true)
  fails=${fails:-?}
  passes=${passes:-?}
  echo "| $label | $idx | ${dur}s | $exit_code | $passes | $fails |" >> "$RESULTS"
  echo "[$(date +%H:%M:%S)] $label run $idx: ${dur}s exit=$exit_code passed=$passes failed=$fails"
}

# Quiesce: wait until any leftover validation vitest finishes.
for _ in $(seq 1 30); do
  if pgrep -f "vitest run" > /dev/null 2>&1; then sleep 10; else break; fi
done

for setting in default 2 4 6 8; do
  if [[ "$setting" == "default" ]]; then cfg="vitest.config.bench-default.ts"; else cfg="vitest.config.bench-${setting}.ts"; fi
  echo "=== Setting: $setting (cfg=$cfg) ==="
  for i in 1 2 3; do
    run_once "$setting" "$i" "$cfg"
  done
done

# Cleanup side-car configs.
rm -f vitest.config.bench-default.ts vitest.config.bench-2.ts vitest.config.bench-4.ts vitest.config.bench-6.ts vitest.config.bench-8.ts

echo >> "$RESULTS"
echo "Finished: $(date -Iseconds)" >> "$RESULTS"
echo "DONE" > "$LOGDIR/STATUS"
