CREATE TABLE IF NOT EXISTS bowler_teams (
  id SERIAL PRIMARY KEY,
  bowler_id INTEGER NOT NULL REFERENCES bowlers(id) ON DELETE CASCADE,
  team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  league_id INTEGER NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  active BOOLEAN NOT NULL DEFAULT true,
  "order" INTEGER NOT NULL DEFAULT 0,
  UNIQUE(bowler_id, team_id)
);